### ISSUE TITLE
Side effect of os.path.exists on GetAttributes for directory junctions

### ISSUE THREAD

**Issue by xchardon** [sunshowers-code/py-ntfs#4]
On my computer, I have a strange effect when using os.path.exists on a directory junction: for about 10 seconds after using it, the GetAttributes function returns the attributes of the target.
So the function "isJunction" fails because it checks os.path.exists, then calls GetAttributes and gets the attributes of the target, which is a directory, not a junction.
I'm using python 3.2 on windows seven 64 bits. The directory junctions are on a network drive, the server is running windows server 2008r2.

I suggest checking the existence of the path directly with the attributes like this:
def isjunction(path):
    attrs = fs.GetFileAttributes(path)
    if attrs==0xffffffff or not fs.junctions_supported(path):
        return False

```
return bool((attrs & fs.FILE_ATTRIBUTE_DIRECTORY) and
            (attrs & fs.FILE_ATTRIBUTE_REPARSE_POINT))
```

0xffffffff is the constant INVALID_FILE_ATTRIBUTES, that is not defined anywhere I think.

**Comment by miigotu** [comment]
Had to +1 you for `haven't had a working Windows development environment for several months`
Same here, which brought me to this module as a potential solution for some windows users in SickRage xD.

**Comment by sunshowers** [comment]
Going to close this since there was no feedback for almost 8 years.
